services:
  mysql:
    image: mysql:8.4
    container_name: eguarantee-mysql
    restart: unless-stopped
    env_file:
      - .env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eguarantee-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      SERVER_PORT: 8081
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:8.8.0
    container_name: eguarantee-redis
    ports:
      - "6381:6379"
volumes:
  mysql_data:
